#define TOG_LAYER_CLR TOGGLE_LAYER_COLOR
#define KC_PREV_TRACK KC_MEDIA_PREV_TRACK
#define KC_NEXT_TRACK KC_MEDIA_NEXT_TRACK
#define KC_PLAY_PAUSE KC_MEDIA_PLAY_PAUSE
#define KC_VOL_UP     KC_AUDIO_VOL_UP
#define KC_VOL_DOWN   KC_AUDIO_VOL_DOWN
#define KC_MUTE       KC_AUDIO_MUTE
